name: lando
recipe: laravel
config:
  webroot: public
  database: mariadb:10.2
excludes:
  - vendor
  - node_modules
events:
  post-start:
    - appserver: php /app/artisan migrate
    - node: yarn production
services:
  cache:
    type: redis:5
  node:
    type: node
    build:
      - yarn
  appserver:
    build:
      - mkdir -p /var/www/.platformsh/bin
      - curl -fsSL -o /var/www/.platformsh/bin/platform https://github.com/platformsh/platformsh-cli/releases/download/v3.40.4/platform.phar
      - chmod ug+x /var/www/.platformsh/bin/platform
      - composer install
      - cp -n .env.lando .env
tooling:
  yarn:
    service: node
  platform:
    service: appserver
    description: Run Platform CLI commands
    cmd: /var/www/.platformsh/bin/platform
  setup:
    service: appserver
    cmd: /app/scripts/platform-setup.sh
    level: app
    options:
      force:
        boolean: true
        default: false
        describe: Force the setup even if its already been run
      github-token:
        string: true
        passthrough: true
        describe: The GitHub API token
        interactive:
          required: true
          type: password
          message: What is the GitHub API token?
          weight: 200
      github-slug:
        string: true
        passthrough: true
        describe: The GitHub repo slug in the form OWNER/REPO eg lando/website
        interactive:
          required: true
          type: input
          message: What is the GitHub repo slug (owner/repo)?
          weight: 300
      name:
        string: true
        passthrough: true
        describe: The name of the Platform.sh instance to spin up
        interactive:
          required: true
          type: input
          message: What do you want to call this Platform.sh project?
          weight: 400
      plan:
        array: true
        choices:
          - development
          - small
          - medium
          - large
        passthrough: true
        describe: The Platform.sh project plan
        interactive:
          required: true
          choices:
            - development
            - small
            - medium
            - large
          default: us-2.platform.sh
          type: list
          message: What kind of plan should the Platform.sh project be?
          weight: 500
      region:
        array: true
        choices:
          - au.platform.sh
          - ca-1.platform.sh
          - eu-2.platform.sh
          - us-2.platform.sh
        passthrough: true
        describe: The region in which to spin up the Platform.sh project
        interactive:
          required: true
          choices:
            - name: Dundee
              value: au.platform.sh
            - name: Trudeau
              value: ca-1.platform.sh
            - name: Merkel
              value: eu-2.platform.sh
            - name: Trump
              value: us-2.platform.sh
          default: us-2.platform.sh
          type: list
          message: In which region do you want to spin up the Platform.sh project?
          weight: 600
      reynolds-token:
        string: true
        passthrough: true
        describe: The Platform.sh Reynoldstoken
        interactive:
          required: true
          type: password
          message: What is the Reynoldstoken?
          weight: 100
      reynolds-validator:
        string: true
        passthrough: true
        default: alec@thinktandem.io
        describe: An email to validate the reynolds token against
      user:
        string: true
        passthrough: true
        describe: The email of a user account you want
      yes:
        boolean: true
        describe: Answer yes to all the questions

